### PR TITLE
feat: add new request auth server; fix: change logic work with token

### LINKED ISSUE #348: Investigate: Invitation address query behavior
Fix the invitation section query bug

- check endpoints for apartments addresses query on the server
- add new one more action for query
- add render logic in the view component
- check usability of a component

### PR DESCRIPTION
**Pull request by yevhendevbox**
dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

### CODE REVIEW

File: src/core/api/http-common.ts [hunk 1]
```diff
@@ -1,5 +1,5 @@
-import axios from 'axios';
-import { authToken } from '@/core/interceptors';
+import axios, { AxiosResponse } from 'axios';
+import { authToken, notValideRefreshToken, notValideToken } from '@/core/interceptors';
```
Comment (aleonovdementiev) [inline src/core/api/http-common.ts]: Maybe you meant 'Valid'?

File: src/store/authorization/actions.ts [hunk 2]
```diff
@@ -25,11 +29,11 @@ export const actions: ActionTree<AuthorizationStateInterface, RootStateInterface
 
         const currentToken = {
```
Comment (aleonovdementiev) [inline src/store/authorization/actions.ts]: Why do you need this variable, if you're not using it anywhere?

File: src/store/localstorage/mutations.ts [hunk 3]
```diff
@@ -4,6 +4,7 @@ import { LocalStorageStateInterface, LocalStorageMutationEnum, Mutations } from
 export const mutations: MutationTree<LocalStorageStateInterface> & Mutations = {
   [LocalStorageMutationEnum.SET_TOKEN]: (state, payload) => {
     localStorage.setItem('user', JSON.stringify(payload));
+    // add refresh token
```
Comment (aleonovdementiev) [inline src/store/localstorage/mutations.ts]: Dou you need this comment here?

**Review by aleonovdementiev — APPROVED** [review]

**Review by korotkovoleksii — APPROVED** [review]
